import math

import tyro

from xrobotoolkit_teleop.hardware.realman_rm65_safe_teleop_controller import (
    RealmanRM65SafeTeleopController,
)


def main(
    arm_host: str = "192.168.10.18",
    arm_port: int = 8080,
    pose_source: str = "right",
    scale_factor: float = 0.25,
    rotation_scale_factor: float = 0.25,
    control_rate_hz: float = 50.0,
    move_v: int = 5,
    move_r: int = 80,
    max_offset_m: float = 0.03,
    max_rot_offset_rad: float = 0.20,
    motion_deadband_m: float = 0.003,
    rot_deadband_rad: float = 0.04,
    grip_on_threshold: float = 0.2,
    grip_off_threshold: float = 0.15,
    use_headset_world_transform: bool = True,
    invert_tcp_xy: bool = False,
    suppress_rotation_during_translation: bool = False,
    freeze_rotation: bool = False,
    send_stop_on_release: bool = True,
    log_motion_debug: bool = False,
    reset_button: str = "B",
    reset_duration_s: float = 3.0,
    xr_watchdog_timeout_s: float = 0.20,
    max_tracking_error_m: float = 0.12,
    max_tracking_error_rad: float = 0.80,
    reset_position_tolerance_m: float = 0.01,
    reset_rotation_tolerance_rad: float = 0.08,
    reset_settle_timeout_s: float = 3.0,
    workspace_min_xyz_m: list[float] | None = None,
    workspace_max_xyz_m: list[float] | None = None,
    motion_command: str = "damped_ik_movej_follow",
    official_ik_tool_or_work: int = 1,
    official_ik_frames_verified: bool = False,
    official_ik_j3_soft_limit_verified: bool = False,
    expected_product_prefix: str = "RM65-B",
    udp_bind_host: str = "0.0.0.0",
    udp_port: int = 8089,
    udp_feedback_timeout_s: float = 0.20,
    max_linear_velocity_m_s: float = 0.05,
    max_linear_acceleration_m_s2: float = 0.40,
    max_angular_velocity_rad_s: float = 0.25,
    max_angular_acceleration_rad_s2: float = 1.20,
    max_xr_step_m: float = 0.05,
    max_xr_rot_step_rad: float = 0.26,
    rotation_full_gain_linear_speed_m_s: float = 0.05,
    rotation_zero_gain_linear_speed_m_s: float = 0.25,
    max_joint_speed_ratio: float = 0.10,
    rearm_stationary_speed_rad_s: float = math.radians(1.0),
    enable_singularity_avoidance: bool = True,
    singularity_slowdown_ratio: float = 0.04,
    singularity_stop_ratio: float = 0.01,
    singularity_slowdown_joint_deg: float = 15.0,
    singularity_stop_joint_deg: float = 5.0,
    singularity_min_speed_scale: float = 0.05,
    singularity_escape_speed_scale: float = 0.10,
    singularity_max_damping: float = 0.08,
    singularity_report_interval_s: float = 2.0,
    dls_compute_budget_s: float = 0.018,
    dls_max_fk_calls: int = 16,
    dls_max_candidate_attempts: int = 3,
    dls_max_consecutive_failures: int = 3,
    dls_work_from_base: list[float] | None = None,
    dls_flange_to_tcp: list[float] | None = None,
    dry_run: bool = False,
    motion_log_path: str = "",
    self_test_ramp: bool = False,
    self_test_axis: str = "+x",
    self_test_distance_m: float = 0.02,
):
    """
    Realman RM65 teleoperation using side-mount XR delta mapping.

    This is the recommended hardware entry. It uses independent UDP feedback,
    bounded velocity/acceleration commands, overspeed latching, and explicit re-arm.

    Use --dry-run --log-motion-debug to preview controller deltas, target poses,
    limited command poses and actual UDP positions at up to 5 Hz without sending motion.
    """
    controller = RealmanRM65SafeTeleopController(
        arm_host=arm_host,
        arm_port=arm_port,
        pose_source=f"{pose_source}_controller",
        control_trigger=f"{pose_source}_grip",
        scale_factor=scale_factor,
        rotation_scale_factor=rotation_scale_factor,
        control_rate_hz=control_rate_hz,
        move_v=move_v,
        move_r=move_r,
        max_offset_m=max_offset_m,
        max_rot_offset_rad=max_rot_offset_rad,
        motion_deadband_m=motion_deadband_m,
        rot_deadband_rad=rot_deadband_rad,
        grip_on_threshold=grip_on_threshold,
        grip_off_threshold=grip_off_threshold,
        use_headset_world_transform=use_headset_world_transform,
        invert_tcp_xy=invert_tcp_xy,
        suppress_rotation_during_translation=suppress_rotation_during_translation,
        freeze_rotation=freeze_rotation,
        send_stop_on_release=send_stop_on_release,
        log_motion_debug=log_motion_debug,
        reset_button=reset_button,
        reset_duration_s=reset_duration_s,
        xr_watchdog_timeout_s=xr_watchdog_timeout_s,
        max_tracking_error_m=max_tracking_error_m,
        max_tracking_error_rad=max_tracking_error_rad,
        reset_position_tolerance_m=reset_position_tolerance_m,
        reset_rotation_tolerance_rad=reset_rotation_tolerance_rad,
        reset_settle_timeout_s=reset_settle_timeout_s,
        workspace_min_xyz_m=workspace_min_xyz_m,
        workspace_max_xyz_m=workspace_max_xyz_m,
        motion_command=motion_command,
        official_ik_tool_or_work=official_ik_tool_or_work,
        official_ik_frames_verified=official_ik_frames_verified,
        official_ik_j3_soft_limit_verified=official_ik_j3_soft_limit_verified,
        expected_product_prefix=expected_product_prefix,
        udp_bind_host=udp_bind_host,
        udp_port=udp_port,
        udp_feedback_timeout_s=udp_feedback_timeout_s,
        max_linear_velocity_m_s=max_linear_velocity_m_s,
        max_linear_acceleration_m_s2=max_linear_acceleration_m_s2,
        max_angular_velocity_rad_s=max_angular_velocity_rad_s,
        max_angular_acceleration_rad_s2=max_angular_acceleration_rad_s2,
        max_xr_step_m=max_xr_step_m,
        max_xr_rot_step_rad=max_xr_rot_step_rad,
        rotation_full_gain_linear_speed_m_s=rotation_full_gain_linear_speed_m_s,
        rotation_zero_gain_linear_speed_m_s=rotation_zero_gain_linear_speed_m_s,
        max_joint_speed_ratio=max_joint_speed_ratio,
        rearm_stationary_speed_rad_s=rearm_stationary_speed_rad_s,
        enable_singularity_avoidance=enable_singularity_avoidance,
        singularity_slowdown_ratio=singularity_slowdown_ratio,
        singularity_stop_ratio=singularity_stop_ratio,
        singularity_slowdown_joint_deg=singularity_slowdown_joint_deg,
        singularity_stop_joint_deg=singularity_stop_joint_deg,
        singularity_min_speed_scale=singularity_min_speed_scale,
        singularity_escape_speed_scale=singularity_escape_speed_scale,
        singularity_max_damping=singularity_max_damping,
        singularity_report_interval_s=singularity_report_interval_s,
        dls_compute_budget_s=dls_compute_budget_s,
        dls_max_fk_calls=dls_max_fk_calls,
        dls_max_candidate_attempts=dls_max_candidate_attempts,
        dls_max_consecutive_failures=dls_max_consecutive_failures,
        dls_work_from_base=dls_work_from_base,
        dls_flange_to_tcp=dls_flange_to_tcp,
        dry_run=dry_run,
        motion_log_path=motion_log_path,
        self_test_ramp=self_test_ramp,
        self_test_axis=self_test_axis,
        self_test_distance_m=self_test_distance_m,
    )
    controller.run()


if __name__ == "__main__":
    tyro.cli(main)
